---
title: "RAMP Analyze Phyloseq"
output: html_document
date: '2022-08-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(phyloseq)
library(cowplot)
library(vegan)
library(corncob)
library(picante)
library(Maaslin2)
library(phyloseqCompanion)
library(coda)
library(CoDaSeq)

select <- dplyr::select
```

```{r load_metadata}
final_participant_list = read.csv('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/metadata/RAMP_final_participant_list.csv')

ramp_metadata_df = read.csv('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/metadata/RAMP_participant_metadata.csv') %>%
  mutate(participant_id = factor(participant_id),
         final_grp = factor(final_grp, levels=c('Placebo', 'Low Dose 2FL', 'High Dose 2FL'))) 

final_participant_timepoint = read.csv('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/metadata/RAMP_final_participant_timepoint.csv') 

ramp_metadata_all_timepoints = final_participant_timepoint %>% 
  rowwise() %>%
  mutate(participant_id = strsplit(participant_timepoint, '_')[[1]][1],
         timepoint = strsplit(participant_timepoint, '_')[[1]][2]) %>%
  left_join(ramp_metadata_df) %>%
  mutate(participant_id = factor(participant_id),
         final_grp = factor(final_grp, levels=c('Placebo', 'Low Dose 2FL', 'High Dose 2FL')))

ramp_16S_mapping_df = read_csv('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/metadata/RAMP_16S_sample_key.csv') %>%
  rowwise() %>%
  na.omit() %>%
  mutate(participant_id = as.factor(participant_id),
         stool_id = as.character(stool_id),
         timepoint = strsplit(stool_id, '')[[1]][1],
         timepoint = factor(timepoint, levels=c('1','2','3','4','5')),
         sample_id = paste0('S', sample_id)) %>%
  filter(sample_id != 'SNA') %>%
  left_join(ramp_metadata_df) %>%
  arrange(sample_id) %>%
  # These sample IDs are each duplicated in our tracking spreadsheet. 
  # We must exclude them as we don't know which is which. 
  filter(!sample_id %in% c('S186', 'S196')) %>%
  filter(!is.na(timepoint)) %>%
  column_to_rownames(var='sample_id') 
```


```{r 16S_diversity_analysis}
# Load base phyloseq object from DADA2 pipeline.
ramp_phyloseq = readRDS("/home/mmcarter/user_data/Projects/RAMP/16S/03.output/220819_ramp_phyloseq_obj.rds")

# Only keep taxa that have at least 5 reads in at least 10% of all samples
ramp_ps_trim = filter_taxa(ramp_phyloseq, function(x) sum(x >= 1) > (0.10*length(x)), TRUE)

sample_data(ramp_ps_rel_ab)

taxa_names(ramp_ps_trim) <- paste0("OTU.", seq(ntaxa(ramp_ps_trim)))

# Make log-transformed phyloseq object.
ramp_ps_log <- transform_sample_counts(ramp_ps_trim, function(x) log2(1 + x))

# Make relative abundance phyloseq object.
ramp_ps_rel_ab <- transform_sample_counts(ramp_ps_trim, function(x) x / sum(x))

# Rarefy to read depth that is equivalent to 10th percentile of all samples. This excludes 12 samples.
ramp_ps_rare <- rarefy_even_depth(ramp_ps_trim, rngseed=1, sample.size=quantile(sample_sums(ramp_ps_trim),prob=0.05), replace=F)

# faiths_pd = picante::pd(samp = otu_table(ramp_ps_rare), tree = phy_tree(ramp_ps_rare), include.root = F) %>%
#   tibble::rownames_to_column(var='SampleID') %>%
#   dplyr::rename(Faith = 2)

#Calculate diversity and bind to sample data frme
ramp_diversity_df <- estimate_richness(ramp_ps_rare, measures = c("Observed","Shannon", "Simpson", "Fisher", "Chao1", "InvSimpson")) %>%
  tibble::rownames_to_column(var='SampleID') %>%
  # left_join(faiths_pd) %>%
  rowwise() 

# Merge diversity information with meta data
ramp_metadata_with_diversity_df = ramp_16S_mapping_df %>%
  rownames_to_column(var='SampleID') %>%
  left_join(ramp_diversity_df, by='SampleID') %>%
  arrange(participant_id, timepoint)
```


```{r alpha_diversity_analysis}
# saveRDS(ramp_metadata_with_diversity_df, file = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/16S_metadata_with_diversity_all.rds')

# Plot observed species histogram for all samples
ggplot(ramp_metadata_with_diversity_df, aes(x=Observed)) +
  geom_histogram(bins=20) +
  theme_bw() +
  xlab('Oberved ASVs') +
  ylab('Number of samples') +
  ggtitle('Histogram of observed ASVs per sample')

# Plot Shannon diverity over time by treatment groups
alpha_diversity_plot = ggplot(ramp_metadata_with_diversity_df, aes(x=timepoint, y=Shannon, fill=final_grp)) +
  geom_boxplot() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "right",
        axis.text.x = element_text(angle = 335, hjust=0)) +
  ylab('Shannon Diversity') +
  # ylim(5, 7) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  scale_x_discrete(name='Timepoint', labels=c('Baseline (Week -2)', 'Baseline (Week 0)', 'Midpoint (Week 3)', 'End (Week 6)', 'Washout (Week 10)'))

# ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_alpha_diversity_plot.pdf',
#        alpha_diversity_plot, width=6, height=4, units = c('in'))



wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'High Dose 2FL') %>% pull(Shannon),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'Placebo') %>% pull(Shannon))
wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'Low Dose 2FL') %>% pull(Shannon),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'Placebo') %>% pull(Shannon))




# Same procedure for Observed Species (richness) as we did for Shannon diversity.
richness_plot = ggplot(ramp_metadata_with_diversity_df, aes(x=timepoint, y=Observed, fill=final_grp)) +
  geom_boxplot() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "right",
        axis.text.x = element_text(angle = 335, hjust=0)) +
  ylab('Observed Species') +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  scale_x_discrete(name='Timepoint', labels=c('Baseline (Week -2)', 'Baseline (Week 0)', 'Midpoint (Week 3)', 'End (Week 6)', 'Washout (Week 10)'))


wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'High Dose 2FL') %>% pull(Observed),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'Placebo') %>% pull(Observed))

wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'Low Dose 2FL') %>% pull(Observed),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(final_grp == 'Placebo') %>% pull(Observed))


```

```{r write_df }

log2_genus_glom_ps = transform_sample_counts(ramp_ps_trim %>% tax_glom("Genus"), function(x) log2(1 + x))

ramp_ps_trim_clr = clr.transform(
  ramp_ps_trim %>% tax_glom("Genus"),
  min_reads = NULL,
  min_prop = 0.001,
  min_occur = 0,
  smpls_by_row = TRUE,
  method = "CZM",
  lab = 0
)

otu_table(ramp_ps_trim_clr)

ramp_ps_genus_rel_ab = otu_table(ramp_ps_trim_clr) %>%
  as.data.frame() 

ppt_timepoint_sample_id_map = ramp_16S_mapping_df %>%
  mutate(participant_timepoint = paste0(participant_id, '_', timepoint)) %>%
  rownames_to_column(var='sample_id') %>%
  select(participant_timepoint, sample_id)

phyloseq_cleaned.imputed = final_participant_timepoint %>%
  left_join(ppt_timepoint_sample_id_map) %>%
  left_join(ramp_ps_genus_rel_ab %>% rownames_to_column(var='sample_id')) %>%
  select(-sample_id) %>%
  column_to_rownames(var='participant_timepoint') %>%
  as.matrix() %>%
  impute.knn()

phyloseq_cleaned_scaled = phyloseq_cleaned.imputed$data %>%
  scale() %>%
  as.data.frame() %>%
  rename_with(~paste0("microbiome_", .), names(.))

write.csv(phyloseq_cleaned_scaled, '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/phyloseq_16S_results_scaled.csv', quote = F, row.names = T)
```

```{r beta_diversity}

# Perform ordinations on individual timepoints
ord2 <- ordinate(subset_samples(ramp_ps_trim, timepoint == 2), "PCoA", "bray")
pcoa_df_tp2 = ord2$vectors %>%
  as.data.frame() %>%
  select(Axis.1, Axis.2, Axis.3, Axis.4) %>%
  rownames_to_column(var='SampleID') %>%
  left_join(ramp_metadata_with_diversity_df)

ord3 <- ordinate(subset_samples(ramp_ps_trim, timepoint == 3), "PCoA", "bray")
pcoa_df_tp3 = ord3$vectors %>%
  as.data.frame() %>%
  select(Axis.1, Axis.2, Axis.3, Axis.4) %>%
  rownames_to_column(var='SampleID') %>%
  left_join(ramp_metadata_with_diversity_df) 

ord4 <- ordinate(subset_samples(ramp_ps_trim, timepoint == 4), "PCoA", "bray")
pcoa_df_tp4 = ord4$vectors %>%
  as.data.frame() %>%
  select(Axis.1, Axis.2, Axis.3, Axis.4) %>%
  rownames_to_column(var='SampleID') %>%
  left_join(ramp_metadata_with_diversity_df) 



# Make plots
pcoa_tp2_labelled = ggplot(pcoa_df_tp2, aes(x=Axis.1, y=Axis.2, color=final_grp)) +
  geom_hline(yintercept=0, linetype='dashed', alpha=0.4, size=0.3) +
  geom_vline(xintercept=0, linetype='dashed', alpha=0.4, size=0.3) +
  geom_point(size=2, alpha=1) +
  theme_bw() +
  scale_color_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylab(paste0('PCo2 [', round(ord2$values$Relative_eig[2] * 100, 1),'%]')) +
  xlab(paste0('PCo1 [', round(ord2$values$Relative_eig[1] * 100, 1),'%]')) + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none") +
  stat_ellipse(type='t') +
  scale_x_continuous(limits = c(-0.45, 0.45)) + 
  scale_y_continuous(limits = c(-0.45, 0.45))

pcoa_tp3_labelled = ggplot(pcoa_df_tp3, aes(x=Axis.1, y=Axis.2, color=final_grp)) +
  geom_hline(yintercept=0, linetype='dashed', alpha=0.4, size=0.3) +
  geom_vline(xintercept=0, linetype='dashed', alpha=0.4, size=0.3) +
  geom_point(size=2, alpha=1) +
  theme_bw() +
  scale_color_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylab(paste0('PCo2 [', round(ord3$values$Relative_eig[2] * 100, 1),'%]')) +
  xlab(paste0('PCo1 [', round(ord3$values$Relative_eig[1] * 100, 1),'%]')) + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none") +
  stat_ellipse(type='t') 

pcoa_tp4_labelled = ggplot(pcoa_df_tp4, aes(x=Axis.1, y=Axis.2, color=final_grp)) +
  geom_hline(yintercept=0, linetype='dashed', alpha=0.4, size=0.3) +
  geom_vline(xintercept=0, linetype='dashed', alpha=0.4, size=0.3) +
  geom_point(size=2, alpha=1) +
  theme_bw() +
  scale_color_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylab(paste0('PCo2 [', round(ord4$values$Relative_eig[2] * 100, 1),'%]')) +
  xlab(paste0('PCo1 [', round(ord4$values$Relative_eig[1] * 100, 1),'%]')) + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title=element_text(size=10),
        axis.ticks = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none") +
  stat_ellipse(type='t') +
  ylim(-0.45, 0.45) +
  xlim(-0.45, 0.45)

# Composite plot
pcoa_composite_labelled = ggdraw() +
  draw_plot(pcoa_tp2_labelled, x=0, y=0.68, width=0.33, height=0.33) +
  draw_plot(pcoa_tp3_labelled, x=0, y=0.34, width=0.33, height=0.33) +
  draw_plot(pcoa_tp4_labelled, x=0, y=0.00, width=0.33, height=0.33)

# ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_pcoa_composite.pdf',
#        pcoa_composite_labelled, width=9, height=6, units=c('in'))


# Adonis tests      
ps_trim_timepoint_1 = subset_samples(ramp_ps_trim, timepoint == 1)
otu_dist_mat_1 <- vegdist(otu_table(ps_trim_timepoint_1))
treatment_fact_1 = sample_data(ps_trim_timepoint_1)$final_grp
adonis2(otu_dist_mat_1 ~ treatment_fact_1, method='bray', perm=5000)

ps_trim_timepoint_2 = subset_samples(ramp_ps_trim, timepoint == 2)
otu_dist_mat_2 <- vegdist(otu_table(ps_trim_timepoint_2))
treatment_fact_2 = sample_data(ps_trim_timepoint_2)$final_grp
adonis2(otu_dist_mat_2 ~ treatment_fact_2, method='bray', perm=5000)

ps_trim_timepoint_3 = subset_samples(ramp_ps_trim, timepoint == 3)
otu_dist_mat_3 <- vegdist(otu_table(ps_trim_timepoint_3))
treatment_fact_3 = sample_data(ps_trim_timepoint_3)$final_grp
adonis2(otu_dist_mat_3 ~ treatment_fact_3, method='bray', perm=5000)

ps_trim_timepoint_4 = subset_samples(ramp_ps_trim, timepoint == 4)
otu_dist_mat_4 <- vegdist(otu_table(ps_trim_timepoint_4))
treatment_fact_4 = sample_data(ps_trim_timepoint_4)$final_grp
adonis2(otu_dist_mat_4 ~ treatment_fact_4, method='bray', perm=5000)

ps_trim_timepoint_5 = subset_samples(ramp_ps_trim, timepoint == 5)
otu_dist_mat_5 <- vegdist(otu_table(ps_trim_timepoint_5))
treatment_fact_5 = sample_data(ps_trim_timepoint_5)$final_grp
adonis2(otu_dist_mat_5 ~ treatment_fact_5, method='bray', perm=5000)

# Pairwise adonis tests for timepoints 3 and 4
dim(otu_table(ps_trim_timepoint_3))
tp3_pairwise = as.data.frame(otu_table(ps_trim_timepoint_3)) %>%
  cbind(data.frame(sample_data(ps_trim_timepoint_3)))
pairwiseAdonis::pairwise.adonis2(data[,1:1183]~treatment_grp,data=tp3_pairwise)

tp4_pairwise = as.data.frame(otu_table(ps_trim_timepoint_4)) %>%
  cbind(data.frame(sample_data(ps_trim_timepoint_4)))
pairwiseAdonis::pairwise.adonis2(data[,1:1183]~treatment_grp,data=tp4_pairwise)

# Beta dispersion tests
beta_tp1 <- betadisper(otu_dist_mat_1, data.frame(sample_data(ps_trim_timepoint_1))$final_grp)
permutest(beta_tp1)
boxplot(beta_tp1)

beta_tp2 <- betadisper(otu_dist_mat_2, data.frame(sample_data(ps_trim_timepoint_2))$final_grp)
permutest(beta_tp2)
boxplot(beta_tp2)

beta_tp3 <- betadisper(otu_dist_mat_3, data.frame(sample_data(ps_trim_timepoint_3))$final_grp)
permutest(beta_tp3)
boxplot(beta_tp3)

beta_tp4 <- betadisper(otu_dist_mat_4, data.frame(sample_data(ps_trim_timepoint_4))$final_grp)
permutest(beta_tp4)
boxplot(beta_tp4)

beta_tp5 <- betadisper(otu_dist_mat_5, data.frame(sample_data(ps_trim_timepoint_5))$final_grp)
permutest(beta_tp5)
boxplot(beta_tp5)
```

```{r maaslin_prep}
taxa_names(ramp_ps_trim) <- paste0("OTU.", seq(ntaxa(ramp_ps_trim)))

ramp_ps_trim_family_glom = ramp_ps_trim %>% tax_glom("Family")
ramp_ps_trim_genus_glom = ramp_ps_trim %>% tax_glom("Genus")
ramp_ps_trim_species_glom = ramp_ps_trim %>% tax_glom("Species")

# tax_table(ramp_ps_trim_genus_glom)

# saveRDS(ramp_ps_trim_genus_glom, '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/phyloseq_object_trimmed_genus_glom.rds')
# saveRDS(ramp_ps_trim_species_glom, '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/phyloseq_object_trimmed_species_glom.rds')
```

```{r maaslin}

# Subset phyloseq object to Week 0 baseline and two intervention timepoints
ps_maaslin = subset_samples(ramp_ps_trim_genus_glom, (timepoint == 2 | timepoint == 3 | timepoint == 4))
tax_table(ps_maaslin)

# saveRDS(ps_maaslin, file = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/phyloseq_object_for_maaslin.rds')
# 
# saveRDS(ramp_ps_trim_genus_glom, file = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/phyloseq_object_for_maaslin_all.rds')

# Recode timepoint variable as continuous variable
df_input_metadata = data.frame(sample_data(ps_maaslin)) %>%
  mutate(final_grp = as.character(final_grp),
         timepoint = as.character(timepoint),
         grp_time = paste0(final_grp, '_', timepoint),
         num_time = case_when(
           timepoint == 1 ~ -2,
           timepoint == 2 ~ 0,
           timepoint == 3 ~ 3,
           timepoint == 4 ~ 6,
           timepoint == 5 ~ 10
         ))

# Run Maaslin2
mas_1 <- Maaslin2(
  input_data = data.frame(otu_table(ps_maaslin)),
  input_metadata = df_input_metadata,
  output = "/home/mmcarter/user_data/Projects/RAMP/16S/MAASLIN/",
  min_abundance = 0.0,
  min_prevalence = 0.1,
  normalization = "TSS",
  transform = "NONE",
  analysis_method = "LM",
  max_significance = 0.05,
  fixed_effects = c("final_grp", "timepoint", "num_time"),
  random_effects = c("participant_id"),
  reference = c("final_grp,Placebo"),
  correction = "BH",
  standardize = FALSE,
  cores = 1)
```


```{r bifido_plotting}

ramp_ps_trim_genus_rel_ab = transform_sample_counts(ramp_ps_trim_genus_glom, function(x) x / sum(x))
tax_table(ramp_ps_trim_genus_rel_ab)


taxa_of_interest = otu_table(ramp_ps_trim_genus_rel_ab)[, 'OTU.191'] %>% 
  as.data.frame() %>%
  rename(OTU_abund = 1) %>%
  rownames_to_column(var='SampleID') %>%
  left_join(ramp_16S_mapping_df %>% rownames_to_column(var='SampleID'), by='SampleID') %>%
  group_by(participant_id) %>%
  arrange(participant_id, timepoint)

taxa_of_interest %>%
  filter(timepoint == 3) %>%
  group_by(final_grp) %>%
  dplyr::summarise(m = 100*mean(OTU_abund),
                   se = 100*sd(OTU_abund)/sqrt(n()))


bifido_abundance_plot = ggplot(taxa_of_interest, aes(x=timepoint, y=OTU_abund*100, fill=final_grp)) +
  geom_boxplot(draw_quantiles=c(0.5)) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  ylab('Bifidobacterium relative abundance (%)') +
  scale_x_discrete(name='Timepoint', labels=c('Baseline\n(Week -2)', 'Baseline\n(Week 0)', 'Midpoint\n(Week 3)', 'End\n(Week 6)', 'Washout\n(Week 10)')) +
  ylim(0, 45) +
  guides(fill=FALSE) 

bifido_abundance_plot_with_covid_deviation = bifido_abundance_plot +
  facet_wrap(~covid_deviation)

# ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_bifidobacterium_abund.pdf',
#        bifido_abundance_plot, width=6, height=4, units = c('in'))

wilcox_list = c()
for (i in 1:5) {
  x1 = wilcox.test(taxa_of_interest %>% filter(timepoint == i) %>% filter(final_grp == 'Placebo') %>% pull(OTU_abund),
       taxa_of_interest %>% filter(timepoint == i) %>% filter(final_grp == 'High Dose 2FL') %>% pull(OTU_abund))
  x2 = wilcox.test(taxa_of_interest %>% filter(timepoint == i) %>% filter(final_grp == 'Low Dose 2FL') %>% pull(OTU_abund),
       taxa_of_interest %>% filter(timepoint == i) %>% filter(final_grp == 'High Dose 2FL') %>% pull(OTU_abund))
  x3 = wilcox.test(taxa_of_interest %>% filter(timepoint == i) %>% filter(final_grp == 'Low Dose 2FL') %>% pull(OTU_abund),
       taxa_of_interest %>% filter(timepoint == i) %>% filter(final_grp == 'Placebo') %>% pull(OTU_abund))
  
  wilcox_list = c(wilcox_list, x1$p.value, x2$p.value, x3$p.value)
}

p.adjust(wilcox_list, method='fdr')

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '91') %>% filter(timepoint == 3) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '92') %>% filter(timepoint == 3) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '91') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '92') %>% filter(timepoint == 3) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '92') %>% filter(timepoint == 4) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 4) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '92') %>% filter(timepoint == 2) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 2) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 1) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 2) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 5) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '91') %>% filter(timepoint == 3) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '91') %>% filter(timepoint == 4) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(treatment_grp == '91') %>% filter(timepoint == 5) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(treatment_grp == '91') %>% filter(timepoint == 4) %>% pull(OTU_abund))


```

```{r metabolon_results}
metabolon_results = read_csv(file = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/2FL_QUANT/2FL_QUANT_metabolon_results.csv') %>%
  mutate(Result = ifelse(Result == 'N/Q', '0', Result)) %>%
  mutate(Result = as.numeric(Result)) %>%
  mutate(Result = ifelse(Result < LLOQ, LLOQ, Result)) %>%
  rename(participant_id = `Client Sample ID`) %>%
  rowwise() %>%
  mutate(participant_id = as.character(participant_id)) %>%
  select(participant_id, Matrix, Result) %>% 
  spread(key='Matrix', value='Result', fill=NA) %>%
  rename(EDTA_plasma = `EDTA plasma`)

```


```{r bifido_responder_subsetting}

bifido_abund_matrix = taxa_of_interest %>% 
  select(c(participant_id, final_grp, timepoint, OTU_abund)) %>%
  spread(key='timepoint', val='OTU_abund', fill=NA) %>%
  filter(participant_id %in% final_participant_list$participant_id) %>%
  select(-final_grp) %>%
  # filter(participant_id != '4011') %>%
  column_to_rownames(var='participant_id') %>%
  as.matrix()

bifido_abund_matrix.imputed <- impute.knn(as.matrix(bifido_abund_matrix))

bifido_delta_df = bifido_abund_matrix.imputed$data %>%
  as.data.frame() %>%
  rownames_to_column(var='participant_id') %>%
  left_join(ramp_metadata_df) %>%
  filter(final_grp != 'Placebo') %>%
  mutate(delta_2_3 = case_when(
    !is.na(`2`) ~ `3` - `2`,
    !is.na(`1`) ~ `3` - `1`
  )) %>%
  rename(bifido_abund_2 = `2`,
         bifido_abund_3 = `3`,
         bifido_abund_4 = `4`) %>%
  select(participant_id, final_grp, bifido_abund_2, bifido_abund_3, bifido_abund_4, delta_2_3)

responder_threshold_delta = bifido_delta_df %>% pull(delta_2_3) %>% quantile(0.5, na.rm=T)

bifido_responders = bifido_delta_df %>%
  mutate(responder_status_delta = ifelse(delta_2_3 >= responder_threshold_delta, 'responder', 'nonresponder')) %>%
  full_join(metabolon_results) %>%
  filter(!is.na(responder_status_delta))

bifido_responders %>%
  arrange(delta_2_3) %>%
  select(participant_id, final_grp, delta_2_3)

bifido_responders %>% 
  group_by(responder_status_delta) %>%
  dplyr::summarise(n())

bifido_responders %>% 
  group_by(responder_status_delta, final_grp) %>%
  dplyr::summarise(n())

write.csv(bifido_responders, file = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/16S_bifido_responder_status.csv', quote = F, row.names = F)

wilcox.test(bifido_responders %>% filter(final_grp == 'Placebo') %>% pull(delta_2_3),
            bifido_responders %>% filter(final_grp == 'High Dose 2FL') %>% pull(delta_2_3), na.rm = T)

wilcox.test(bifido_responders %>% filter(final_grp == 'Placebo') %>% pull(delta_2_3),
            bifido_responders %>% filter(final_grp == 'Low Dose 2FL') %>% pull(delta_2_3), na.rm = T)

wilcox.test(bifido_responders %>% filter(final_grp == 'High Dose 2FL') %>% pull(delta_2_3),
            bifido_responders %>% filter(final_grp == 'Low Dose 2FL') %>% pull(delta_2_3), na.rm = T)

bifido_abund_change_with_color = ggplot(bifido_responders %>% mutate(final_grp = factor(final_grp, levels=c('Low Dose 2FL', 'High Dose 2FL'))), aes(x=final_grp, y=delta_2_3)) +
  geom_hline(yintercept=0) +
  geom_violin(draw_quantiles = c(0.5)) +
  geom_jitter(aes(color=responder_status_delta), width=0.15) +
  geom_hline(yintercept=responder_threshold_delta, linetype='dashed') +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  xlab('Treatment Group') + 
  ylab('Change in Bifidobacterium abundance\nfrom Week 0 to Week 3 (%)') +
  scale_color_manual(values=c('#d75e65', '#5e65d7')) +
  scale_y_continuous(limits=c(-0.12, 0.2), breaks=c(-0.1, 0, 0.1, 0.2), labels=c('-10', '0', '10', '20')) +
  guides(color=FALSE)

ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_bifido_abund_change_with_color.pdf', plot = bifido_abund_change_with_color, units=c('in'), width=4, height=3)

bifido_responder_at_baseline = ggplot(bifido_responders, aes(x=responder_status_delta, y=bifido_abund_2)) +
  geom_boxplot(aes(fill=responder_status_delta)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  xlab('Responder Status') + 
  ylab('Bifidobacterium abundance at baseline') +
  scale_fill_manual(values=c('#d75e65', '#5e65d7')) +
  scale_y_continuous(limits=c(0, 0.32), breaks=c(0, 0.1, 0.2, 0.3), labels=c('0', '10', '20', '30')) +
  guides(fill=FALSE)
# 
ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_bifido_responder_baseline.pdf', plot = bifido_responder_at_baseline, units=c('in'), width=2.5, height=3.5)

wilcox.test(bifido_responders %>% filter(responder_status_delta == 'responder') %>% pull(bifido_abund_2),
            bifido_responders %>% filter(responder_status_delta == 'nonresponder') %>% pull(bifido_abund_2))


bifido_responder_plasma_levels = ggplot(bifido_responders, aes(x=responder_status_delta, y=EDTA_plasma, fill=responder_status_delta)) +
  geom_hline(yintercept=0.02, linetype='dashed') +
  geom_boxplot() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  xlab('Responder Status') +
  ylab('Plasma 2FL concentration (ug/mL)') +
  scale_fill_manual(values=c('#d75e65', '#5e65d7')) +
  guides(fill=FALSE) +
  ylim(0, 0.35)

wilcox.test(bifido_responders %>% filter(responder_status_delta == 'responder') %>% pull(EDTA_plasma),
            bifido_responders %>% filter(responder_status_delta == 'nonresponder') %>% pull(EDTA_plasma))

ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_bifido_responder_plasma_levels.pdf', plot = bifido_responder_plasma_levels, units=c('in'), width=2.5, height=3.5)
```


```{r bifido_species_plotting}
ramp_ps_trim_species_glom

ramp_ps_trim_species_glom_rel_ab = transform_sample_counts(ramp_ps_trim_species_glom, function(x) x / sum(x))

bifido_species = tax_table(ramp_ps_trim_species_glom_rel_ab) %>%
  as.data.frame() %>%
  filter(grepl('Bifido', Genus)) %>%
  rownames()

bifido_species_taxa_of_interest = otu_table(ramp_ps_trim_species_glom_rel_ab)[, c(bifido_species)] %>% 
  as.data.frame() %>%
  rownames_to_column(var='SampleID') %>%
  gather(key='OTU', value='abundance', -SampleID) %>%
  left_join(ramp_16S_mapping_df %>% rownames_to_column(var='SampleID'), by='SampleID') %>%
  group_by(participant_id) %>%
  arrange(participant_id, timepoint) 


bifido_abundance_plot = ggplot(bifido_species_taxa_of_interest, aes(x=timepoint, y=abundance*100, fill=final_grp)) +
  geom_boxplot(draw_quantiles=c(0.5)) +
  facet_wrap(~OTU) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  ylab('Bifidobacterium relative abundance (%)') +
  scale_x_discrete(name='Timepoint', labels=c('Baseline\n(Week -2)', 'Baseline\n(Week 0)', 'Midpoint\n(Week 3)', 'End\n(Week 6)', 'Washout\n(Week 10)')) +
  ylim(0, 45) +
  guides(fill=FALSE)

# ggsave('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_bifido_species_plots.pdf', 
#        bifido_abundance_plot, width=9, height=5)

wilcox.test(bifido_species_taxa_of_interest %>% filter(treatment_grp == '92') %>% filter(OTU == 'OTU.191') %>% filter(timepoint == 3) %>% pull(abundance),
            bifido_species_taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(OTU == 'OTU.191') %>% filter(timepoint == 3) %>% pull(abundance))

wilcox.test(bifido_species_taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(OTU == 'OTU.191') %>% filter(timepoint == 2) %>% pull(abundance),
            bifido_species_taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(OTU == 'OTU.191') %>% filter(timepoint == 3) %>% pull(abundance))


wilcox.test(bifido_species_taxa_of_interest %>% filter(treatment_grp == '92') %>% filter(OTU == 'OTU.559') %>% filter(timepoint == 3) %>% pull(abundance),
            bifido_species_taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(OTU == 'OTU.559') %>% filter(timepoint == 3) %>% pull(abundance))

wilcox.test(bifido_species_taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(OTU == 'OTU.559') %>% filter(timepoint == 2) %>% pull(abundance),
            bifido_species_taxa_of_interest %>% filter(treatment_grp == '93') %>% filter(OTU == 'OTU.559') %>% filter(timepoint == 3) %>% pull(abundance))
```


```{r protocol_deviation_analysis}
## ALPHA DIVERSITY 

# Plot Shannon diverity over time by treatment groups
alpha_diversity_covid_deviations = ggplot(ramp_metadata_with_diversity_df, aes(x=timepoint, y=Shannon, fill=final_grp)) +
  geom_boxplot() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "right") +
  ylab('Shannon Diversity') +
  ylim(5, 7) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  scale_x_discrete(name='Timepoint', labels=c('Baseline\n(Week -2)', 'Baseline\n(Week 0)', 'Midpoint\n(Week 3)', 'End\n(Week 6)', 'Washout\n(Week 10)')) +
  guides(fill=FALSE) +
  facet_wrap(~covid_deviation)

ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_alpha_diversity_covid_deviations.pdf',
       alpha_diversity_covid_deviations, width=10, height=4, units = c('in'))



wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == TRUE) %>% filter(final_grp == 'High Dose 2FL') %>% pull(Shannon),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == TRUE) %>% filter(final_grp == 'Placebo') %>% pull(Shannon))
wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == TRUE) %>% filter(final_grp == 'Low Dose 2FL') %>% pull(Shannon),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == TRUE) %>% filter(final_grp == 'Placebo') %>% pull(Shannon))

wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == FALSE) %>% filter(final_grp == 'High Dose 2FL') %>% pull(Shannon),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == FALSE) %>% filter(final_grp == 'Placebo') %>% pull(Shannon))
wilcox.test(ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == FALSE) %>% filter(final_grp == 'Low Dose 2FL') %>% pull(Shannon),
            ramp_metadata_with_diversity_df %>% filter(timepoint == 3) %>% filter(covid_deviation == FALSE) %>% filter(final_grp == 'Placebo') %>% pull(Shannon))



## BIFIDO FINDING
bifido_abundance_covid_deviations = ggplot(taxa_of_interest, aes(x=timepoint, y=OTU_abund*100, fill=final_grp)) +
  geom_boxplot(draw_quantiles=c(0.5)) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  ylab('Bifidobacterium relative abundance (%)') +
  scale_x_discrete(name='Timepoint', labels=c('Baseline\n(Week -2)', 'Baseline\n(Week 0)', 'Midpoint\n(Week 3)', 'End\n(Week 6)', 'Washout\n(Week 10)')) +
  ylim(0, 45) +
  guides(fill=FALSE) +
  facet_wrap(~covid_deviation)

ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/16S_bifidobacterium_abund_covid_deviations.pdf',
       bifido_abundance_covid_deviations, width=10, height=4, units = c('in'))

wilcox.test(taxa_of_interest %>% filter(covid_deviation == TRUE) %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(covid_deviation == TRUE) %>% filter(treatment_grp == '92') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(covid_deviation == FALSE) %>% filter(treatment_grp == '92') %>% filter(timepoint == 3) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(covid_deviation == FALSE) %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund))

wilcox.test(taxa_of_interest %>% filter(covid_deviation == FALSE) %>% filter(treatment_grp == '9') %>% filter(timepoint == 3) %>% pull(OTU_abund),
            taxa_of_interest %>% filter(covid_deviation == TRUE) %>% filter(treatment_grp == '93') %>% filter(timepoint == 3) %>% pull(OTU_abund))

```

