---
title: "RAMP Clinical Data"
output: html_document
date: '2022-08-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Maaslin2)
library(cowplot)

select = dplyr::select
```

```{r load_metadata}
final_participant_list = read.csv('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/metadata/RAMP_final_participant_list.csv')

ramp_metadata_df = read.csv('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/metadata/RAMP_participant_metadata.csv') %>%
  mutate(participant_id = factor(participant_id),
         final_grp = factor(final_grp, levels=c('Placebo', 'Low Dose 2FL', 'High Dose 2FL'))) %>%
  left_join(bifido_responders) %>%
  filter(participant_id %in% final_participant_list$participant_id)

final_participant_timepoint = read.csv('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/metadata/RAMP_final_participant_timepoint.csv') 

ramp_metadata_all_timepoints = final_participant_timepoint %>% 
  rowwise() %>%
  mutate(participant_id = strsplit(participant_timepoint, '_')[[1]][1],
         timepoint = strsplit(participant_timepoint, '_')[[1]][2]) %>%
  left_join(ramp_metadata_df) %>%
  mutate(participant_id = factor(participant_id),
         final_grp = factor(final_grp, levels=c('Placebo', 'Low Dose 2FL', 'High Dose 2FL')))

```


```{r clinical_panel_load_data}
dat.lip = read.csv("/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/CLINICAL_DATA/RAMP_Lipids_RawDATA.csv",header = T) %>%
  select(2:8) %>%
  select(-blood_glucose)
dat.glu = read.csv("/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/CLINICAL_DATA/RAMP_Glucose_RawDATA.csv",header = T)
dat.ins = read.csv("/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/CLINICAL_DATA/RAMP_Insulin_RawDATA.csv",header = T) %>%
  select(2:4)

dat.bmi = read.csv("/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/CLINICAL_DATA/RAMP_BloodPressure_RawDATA.csv",header = T) %>%
  mutate(Height_M = ifelse(Height_M == 0, NA, Height_M)) %>%
  mutate(waist_to_height = WAIST / (100*Height_M)) %>%
  select(c(1, 2, 12, 14, 15, 17)) %>%
  filter(!is.na(Record.ID)) %>%
  rename(record_id = Record.ID) %>% 
  mutate(redcap_event_name = case_when(
    Visit.ID == 'Visit 1' ~ 'baseline_2_arm_1',
    Visit.ID == 'Visit 2' ~ 'baseline_arm_1',
    Visit.ID == 'Visit 3' ~ 'week_3_arm_1',
    Visit.ID == 'Visit 4' ~ 'week_6_arm_1',
    Visit.ID == 'Visit 5' ~ 'week_10_arm_1'
  )) %>%
  select(-c(Visit.ID)) %>%
  rename(weight = WEIGHT.IN.KG, bmi = BMI, waist_circ = WAIST) %>%
  select(c(record_id, redcap_event_name, everything()))


ramp_clinical_data = left_join(dat.lip, dat.glu, by=c('record_id', 'redcap_event_name')) %>%
  left_join(dat.ins, by=c('record_id', 'redcap_event_name')) %>%
  left_join(dat.bmi, by=c('record_id', 'redcap_event_name')) %>%
  rename(participant_id = record_id) %>%
  mutate(participant_id = factor(participant_id)) %>%
  left_join(ramp_metadata_df, by='participant_id') %>%
  filter(participant_id %in% final_participant_list$participant_id) %>%
  filter(redcap_event_name != 'baseline_2b_arm_1') %>%
  mutate(redcap_event_name = factor(redcap_event_name, levels=c('baseline_2_arm_1', 'baseline_arm_1', 'week_3_arm_1', 'week_6_arm_1', 'week_10_arm_1'))) %>%
  mutate(timepoint = case_when(
    redcap_event_name == 'baseline_2_arm_1' ~ '1',
    redcap_event_name == 'baseline_arm_1' ~ '2',
    redcap_event_name == 'week_3_arm_1' ~ '3',
    redcap_event_name == 'week_6_arm_1' ~ '4',
    redcap_event_name == 'week_10_arm_1' ~ '5'
  ),
  participant_timepoint = paste0(participant_id, '_', timepoint))

```

```{r clinical_cleaned_saved}
clinical_results_merged.impute = ramp_clinical_data %>%
  select(participant_timepoint, hdl_cholesterol, calculated_ldl_chol, total_cholesterol, triglycerides, blood_glucose, insulin, weight, bmi, waist_circ, waist_to_height) %>%
  column_to_rownames(var='participant_timepoint') %>%
  rename_with(~paste0("clinical_", .), names(.)) %>%
  as.matrix() %>%
  impute.knn()

clinical_results_cleaned_scaled = clinical_results_merged.impute$data %>%
  scale() %>%
  as.data.frame()

write.csv(clinical_results_cleaned_scaled, '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/CLINICAL_DATA/clinical_results_scaled.csv', quote = F, row.names = T)
```

```{r clinical_panel_analysis}
perc_change = function(input_df, column, grp) {
  data_df = input_df %>% 
    filter(final_grp == grp) %>%
    select(participant_id, redcap_event_name, column) %>%
    rename(value = 3) %>%
    spread(key='redcap_event_name', value='value') %>%
    select(participant_id, baseline_arm_1, week_6_arm_1) %>%
    rowwise() %>%
    mutate(perc_change = (week_6_arm_1 - baseline_arm_1) / baseline_arm_1)
  
  average = mean(data_df$perc_change,na.rm = T)
  num = sum(is.na(data_df$perc_change)==F)
  std_dev = sd(data_df$perc_change, na.rm = T)
  ss = sqrt(num)
  error = qnorm(0.975) * std_dev / ss
  
  high = average + error
  low = average - error
  
  d = data.frame(variable = column, arm = grp, n = num, average_change = average, high = high, low = low, error = error)
  return(d)
}


vars = c('hdl_cholesterol', 'calculated_ldl_chol', 'blood_glucose', 'triglycerides', 'total_cholesterol', 'insulin', 'weight', 'bmi', 'waist_circ', 'waist_to_height')
arms = c('Placebo', 'Low Dose 2FL', 'High Dose 2FL')

ramp_clinical_perc_change_result_df = data.frame(variable = character(0), 
                       arm = character(0), 
                       n = double(0),
                       average_change = double(0), 
                       high = double(0), 
                       low = double(0),
                       error = double(0))
for (v in vars) {
  for (a in arms) {
    df = perc_change(ramp_clinical_data, v, a)
    ramp_clinical_perc_change_result_df = rbind(ramp_clinical_perc_change_result_df, df)
  }
}

ramp_clinical_change_result_df_for_write = ramp_clinical_perc_change_result_df %>% 
  mutate(write_string = paste0(round(average_change*100, 1), ' (', round(low*100, 1), ', ', round(high*100, 1), ')')) %>% 
  mutate(significant = ifelse(sign(high) == sign(low), '*', '')) %>%
  select(variable, arm, n, write_string, significant)

tree_plot_df = ramp_clinical_perc_change_result_df %>%
  rename(final_grp = arm) %>%
  mutate(final_grp = factor(final_grp, levels=c('Placebo', 'Low Dose 2FL', 'High Dose 2FL'))) %>%
  mutate(variable = case_when(
    variable == 'triglycerides' ~ 'Triglycerides',
    variable == 'total_cholesterol' ~ 'Total Cholesterol',
    variable == 'insulin' ~ 'Fasting Insulin',
    variable == 'hdl_cholesterol' ~ 'HDL Cholesterol',
    variable == 'hdl_fraction' ~ 'Total Chol : HDL Ratio',
    variable == 'calculated_ldl_chol' ~ 'LDL Cholesterol',
    variable == 'blood_glucose' ~ 'Blood Glucose',
  )) %>%
  mutate(variable = factor(variable, levels=c('Triglycerides', 'Total Cholesterol', 'HDL Cholesterol', 'LDL Cholesterol', 'Fasting Insulin', 'Blood Glucose')))

clinical_panel_tree_plot = ggplot(tree_plot_df, aes(x=variable, y=average_change, color=final_grp)) +
  geom_point(position = position_dodge(width=0.6) , size=3) +
  geom_errorbar(aes(ymin=average_change-error, ymax=average_change+error), position = position_dodge(width=0.6) , width=0.0, size=2) +
  coord_flip() +
  geom_hline(yintercept=0) + 
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = 'bottom') +
  scale_color_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylab('Percent change (%)') +
  scale_y_continuous(limits=c(-0.1, 0.42), breaks = c(-0.1, 0, 0.1, 0.2, 0.3, 0.4), labels=c('-10', '0', '10', '20', '30', '40')) 

ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/clinical_panel_forest_plot.pdf', plot = clinical_panel_tree_plot, units = c('in'), width=6, height=4)

```


```{r maaslin_for_clinical_data}
ps_maaslin = readRDS('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/phyloseq_object_for_maaslin_all.rds')
tax_table(ps_maaslin)

ramp_ps_trim_genus_glom = readRDS('/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/data/16S/phyloseq_object_trimmed_genus_glom.rds')

# Recode timepoint variable as continuous variable
df_input_metadata = data.frame(sample_data(ps_maaslin)) %>%
  mutate(final_grp = as.character(final_grp),
         timepoint = as.character(timepoint),
         timepoint_text = case_when(
           timepoint == 1 ~ 'baseline_2_arm_1',
           timepoint == 2 ~ 'baseline_arm_1',
           timepoint == 3 ~ 'week_3_arm_1',
           timepoint == 4 ~ 'week_6_arm_1',
           timepoint == 5 ~ 'week_10_arm_1'
         ),
         grp_time = paste0(final_grp, '_', timepoint),
         num_time = case_when(
           timepoint == 1 ~ -2,
           timepoint == 2 ~ 0,
           timepoint == 3 ~ 3,
           timepoint == 4 ~ 6,
           timepoint == 5 ~ 10
         )) %>%
  rownames_to_column(var='SampleID') %>%
  left_join(ramp_clinical_data, by=c('participant_id'='participant_id','timepoint_text'='redcap_event_name')) %>%
  left_join(blood_pressure_df, by=c('participant_id', 'timepoint.x'='timepoint')) %>%
  column_to_rownames(var='SampleID') %>%
  filter(timepoint.x %in% c(1, 2, 3, 4, 5))

ps_maaslin_filtered = data.frame(otu_table(ps_maaslin)[rownames(df_input_metadata),])


# Run Maaslin2
mas_clinical <- Maaslin2(
  input_data = ps_maaslin_filtered,
  input_metadata = df_input_metadata,
  output = "/home/mmcarter/user_data/Projects/RAMP/CLINICALPANEL/MAASLIN",
  min_abundance = 0.0,
  min_prevalence = 0.2,
  normalization = "NONE",
  transform = "NONE",
  analysis_method = "ZINB",
  max_significance = 0.05,
  fixed_effects = c("gender.x", "age.x", "hdl_cholesterol", "ldl_cholesterol", "blood_glucose", "insulin", "bmi"),
  random_effects = c("participant_id"),
  correction = "BH",
  standardize = TRUE,
  cores = 1)

# Run Maaslin2
mas_clinical <- Maaslin2(
  input_data = data.frame(otu_table(ps_maaslin)),
  input_metadata = df_input_metadata,
  output = "/home/mmcarter/user_data/Projects/RAMP/CLINICALPANEL/MAASLIN",
  min_abundance = 0.0,
  min_prevalence = 0.1,
  normalization = "NONE",
  transform = "NONE",
  analysis_method = "NEGBIN",
  max_significance = 0.05,
  fixed_effects = c("gender.x", "calculated_ldl_chol"),
  random_effects = c("participant_id"),
  correction = "BH",
  standardize = TRUE,
  cores = 1)

mas_clinical <- Maaslin2(
  input_data = data.frame(otu_table(ps_maaslin)),
  input_metadata = df_input_metadata,
  output = "/home/mmcarter/user_data/Projects/RAMP/CLINICALPANEL/MAASLIN",
  min_abundance = 0.0,
  min_prevalence = 0.1,
  normalization = "NONE",
  transform = "NONE",
  analysis_method = "NEGBIN",
  max_significance = 0.05,
  fixed_effects = c("triglycerides"),
  random_effects = c("participant_id"),
  correction = "BH",
  standardize = TRUE,
  cores = 1)

mas_clinical <- Maaslin2(
  input_data = data.frame(otu_table(ps_maaslin)),
  input_metadata = df_input_metadata,
  output = "/home/mmcarter/user_data/Projects/RAMP/CLINICALPANEL/MAASLIN",
  min_abundance = 0.0,
  min_prevalence = 0.1,
  normalization = "NONE",
  transform = "NONE",
  analysis_method = "NEGBIN",
  max_significance = 0.05,
  fixed_effects = c("blood_glucose"),
  random_effects = c("participant_id"),
  correction = "BH",
  standardize = TRUE,
  cores = 1)

mas_clinical <- Maaslin2(
  input_data = data.frame(otu_table(ps_maaslin)),
  input_metadata = df_input_metadata,
  output = "/home/mmcarter/user_data/Projects/RAMP/CLINICALPANEL/MAASLIN",
  min_abundance = 0.0,
  min_prevalence = 0.1,
  normalization = "NONE",
  transform = "NONE",
  analysis_method = "NEGBIN",
  max_significance = 0.05,
  fixed_effects = c("insulin"),
  random_effects = c("participant_id"),
  correction = "BH",
  standardize = TRUE,
  cores = 1)

mas_clinical <- Maaslin2(
  input_data = data.frame(otu_table(ps_maaslin)),
  input_metadata = df_input_metadata,
  output = "/home/mmcarter/user_data/Projects/RAMP/CLINICALPANEL/MAASLIN",
  min_abundance = 0.0,
  min_prevalence = 0.1,
  normalization = "NONE",
  transform = "NONE",
  analysis_method = "NEGBIN",
  max_significance = 0.05,
  fixed_effects = c("bp_diastolic"),
  random_effects = c("participant_id"),
  correction = "BH",
  standardize = TRUE,
  cores = 1)


ggplot(mas_clinical$results, aes(x=coef, y=-1*log10(qval), color=metadata)) +
  geom_point() +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_color_brewer(palette='Dark2') +
  ylab('Significance (-log(q-value))')


ramp_ps_trim_clr = clr.transform(
  ps_maaslin,
  min_reads = NULL,
  min_prop = 0.001,
  min_occur = 0,
  smpls_by_row = TRUE,
  method = "CZM",
  lab = 0
)

clinical_phyloseq_joined = df_input_metadata %>%
  rownames_to_column(var='SampleID') %>%
  left_join(data.frame(otu_table(ramp_ps_trim_clr)) %>% rownames_to_column(var='SampleID'))


ggplot(clinical_phyloseq_joined, aes(x=OTU.118, y=hdl_cholesterol)) +
  geom_point() +
  stat_smooth(method='lm')

summary(lm(hdl_cholesterol ~ OTU.118, data=clinical_phyloseq_joined))
```


```{r covid_deviation_analysis}

## WITH DEVIATION 
vars = c('hdl_cholesterol', 'calculated_ldl_chol', 'blood_glucose', 'triglycerides', 'total_cholesterol', 'insulin')
arms = c('Placebo', 'Low Dose 2FL', 'High Dose 2FL')

deviation_ramp_clinical_perc_change_result_df = data.frame(variable = character(0), 
                       arm = character(0), 
                       n = double(0),
                       average_change = double(0), 
                       high = double(0), 
                       low = double(0),
                       error = double(0))
for (v in vars) {
  for (a in arms) {
    df = perc_change(ramp_clinical_data %>% filter(covid_deviation == TRUE), v, a)
    deviation_ramp_clinical_perc_change_result_df = rbind(deviation_ramp_clinical_perc_change_result_df, df)
  }
}

deviation_ramp_clinical_change_result_df_for_write = deviation_ramp_clinical_perc_change_result_df %>% 
  mutate(write_string = paste0(round(average_change*100, 1), ' (', round(low*100, 1), ', ', round(high*100, 1), ')')) %>% 
  mutate(significant = ifelse(sign(high) == sign(low), '*', '')) %>%
  select(variable, arm, n, write_string, significant)


deviation_tree_plot_df = deviation_ramp_clinical_perc_change_result_df %>%
  rename(final_grp = arm) %>%
  mutate(final_grp = factor(final_grp, levels=c('Placebo', 'Low Dose 2FL', 'High Dose 2FL'))) %>%
  mutate(variable = case_when(
    variable == 'triglycerides' ~ 'Triglycerides',
    variable == 'total_cholesterol' ~ 'Total Cholesterol',
    variable == 'insulin' ~ 'Fasting Insulin',
    variable == 'hdl_cholesterol' ~ 'HDL Cholesterol',
    variable == 'hdl_fraction' ~ 'Total Chol : HDL Ratio',
    variable == 'calculated_ldl_chol' ~ 'LDL Cholesterol',
    variable == 'blood_glucose' ~ 'Blood Glucose',
  )) %>%
  mutate(variable = factor(variable, levels=c('Triglycerides', 'Total Cholesterol', 'HDL Cholesterol', 'LDL Cholesterol', 'Fasting Insulin', 'Blood Glucose')))

deviation_clinical_panel_tree_plot = ggplot(deviation_tree_plot_df, aes(x=variable, y=average_change, color=final_grp)) +
  geom_point(position = position_dodge(width=0.6) , size=3) +
  geom_errorbar(aes(ymin=average_change-error, ymax=average_change+error), position = position_dodge(width=0.6) , width=0.0, size=2) +
  coord_flip() +
  geom_hline(yintercept=0) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = 'bottom') +
  scale_color_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylab('Percent change (%)') +
  scale_y_continuous(limits=c(-0.6, 0.6), breaks = c(-0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6), labels=c('-60', '-50', '-40', '-30', '-20', '-10', '0', '10', '20', '30', '40', '50', '60')) 


ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/clinical_panel_forest_deviation.pdf', plot = deviation_clinical_panel_tree_plot, units = c('in'), width=6, height=4)

## WITHOUT DEVIATION

vars = c('hdl_cholesterol', 'calculated_ldl_chol', 'blood_glucose', 'triglycerides', 'total_cholesterol', 'insulin')
arms = c('Placebo', 'Low Dose 2FL', 'High Dose 2FL')

nodeviation_ramp_clinical_perc_change_result_df = data.frame(variable = character(0), 
                       arm = character(0), 
                       n = double(0),
                       average_change = double(0), 
                       high = double(0), 
                       low = double(0),
                       error = double(0))
for (v in vars) {
  for (a in arms) {
    df = perc_change(ramp_clinical_data %>% filter(covid_deviation == FALSE), v, a)
    nodeviation_ramp_clinical_perc_change_result_df = rbind(nodeviation_ramp_clinical_perc_change_result_df, df)
  }
}

nodeviation_ramp_clinical_change_result_df_for_write = nodeviation_ramp_clinical_perc_change_result_df %>% 
  mutate(write_string = paste0(round(average_change*100, 1), ' (', round(low*100, 1), ', ', round(high*100, 1), ')')) %>% 
  mutate(significant = ifelse(sign(high) == sign(low), '*', '')) %>%
  select(variable, arm, n, write_string, significant)


nodeviation_tree_plot_df = nodeviation_ramp_clinical_perc_change_result_df %>%
  rename(final_grp = arm) %>%
  mutate(final_grp = factor(final_grp, levels=c('Placebo', 'Low Dose 2FL', 'High Dose 2FL'))) %>%
  mutate(variable = case_when(
    variable == 'triglycerides' ~ 'Triglycerides',
    variable == 'total_cholesterol' ~ 'Total Cholesterol',
    variable == 'insulin' ~ 'Fasting Insulin',
    variable == 'hdl_cholesterol' ~ 'HDL Cholesterol',
    variable == 'hdl_fraction' ~ 'Total Chol : HDL Ratio',
    variable == 'calculated_ldl_chol' ~ 'LDL Cholesterol',
    variable == 'blood_glucose' ~ 'Blood Glucose',
  )) %>%
  mutate(variable = factor(variable, levels=c('Triglycerides', 'Total Cholesterol', 'HDL Cholesterol', 'LDL Cholesterol', 'Fasting Insulin', 'Blood Glucose')))

nodeviation_clinical_panel_tree_plot = ggplot(nodeviation_tree_plot_df, aes(x=variable, y=average_change, color=final_grp)) +
  geom_point(position = position_dodge(width=0.6) , size=3) +
  geom_errorbar(aes(ymin=average_change-error, ymax=average_change+error), position = position_dodge(width=0.6) , width=0.0, size=2) +
  coord_flip() +
  geom_hline(yintercept=0) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = 'bottom') +
  scale_color_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylab('Percent change (%)') +
  scale_y_continuous(limits=c(-0.2, 0.6), breaks = c(-0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5), labels=c('-20', '-10', '0', '10', '20', '30', '40', '50')) 


ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/clinical_panel_forest_nodeviation.pdf', plot = nodeviation_clinical_panel_tree_plot, units = c('in'), width=6, height=4)

```

```{r clinical_panel_plots}
triglycerides_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=triglycerides)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=40, ymax=150), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('Triglycerides (mg/dL)')

total_chol_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=total_cholesterol)) +
  # geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=125, ymax=200), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('Total Cholesterol (mg/dL)')

ldl_chol_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=calculated_ldl_chol)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=25, ymax=110), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('LDL Cholesterol (mg/dL)')

hdl_chol_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=hdl_cholesterol)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=60, ymax=145), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('HDL Cholesterol (mg/dL)')

fasting_insulin_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=insulin)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=2, ymax=20), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('Fasting Insulin (uU/mL)')


fasting_glucose_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=blood_glucose)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=55, ymax=100), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylim(50, 160) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('Fasting Glucose (mg/dL)')

bmi_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=bmi)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=18.5, ymax=24.9), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylim(18, 38) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('Body Mass Index')

weight_plot = ggplot(ramp_clinical_data, aes(x=redcap_event_name, y=weight)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=0.3, ymax=0.5), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylim(45, 120) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('Body Weight (kg)')

waist_to_height_plot = ggplot(ramp_clinical_data %>% filter(waist_to_height > 0.25), aes(x=redcap_event_name, y=waist_to_height)) +
  geom_rect(mapping=aes(xmin='baseline_2_arm_1', xmax='week_10_arm_1', ymin=0.3, ymax=0.5), fill='#ddf7dd', color='#ddf7dd', alpha=0.1, stat="identity") +
  geom_boxplot(aes(fill=final_grp), alpha=1, outlier.size = 0.5) +
  geom_line(aes(group=participant_id), alpha=0.5, size=0.2) +
  scale_x_discrete(labels=c('-2', '0', '3', '6', '10')) +
  scale_fill_manual(values=c('#939598', '#b4cce1', '#5ea1d7')) +
  ylim(0.3, 0.75) +
  facet_wrap(~final_grp) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(fill = "none") +
  xlab('Weeks') +
  ylab('Waist-to-Height Ratio')


ramp_clinical_panel_composite_plot = ggdraw() +
  draw_plot(triglycerides_plot, x=0, y=0.8, width=0.47, height=0.2) +
  draw_plot(total_chol_plot, x=0.5, y=0.8, width=0.47, height=0.2) +
  draw_plot(ldl_chol_plot, x=0, y=0.6, width=0.47, height=0.2) +
  draw_plot(hdl_chol_plot, x=0.5, y=0.6, width=0.47, height=0.2) +
  draw_plot(fasting_insulin_plot, x=0.0, y=0.4, width=0.47, height=0.2) +
  draw_plot(fasting_glucose_plot, x=0.5, y=0.4, width=0.47, height=0.2) +
  draw_plot(bmi_plot, x=0.0, y=0.2, width=0.47, height=0.2) +
  draw_plot(weight_plot, x=0.5, y=0.2, width=0.47, height=0.2) +
  draw_plot(waist_to_height_plot, x=0.0, y=0.0, width=0.47, height=0.2)

ggsave(filename = '/home/mmcarter/user_data/Projects/RAMP/RAMP_study_analysis/plots/clinical_panel_composite_plot.pdf',
       plot = ramp_clinical_panel_composite_plot,
       width = 10, height = 12, units = c('in'))
```

